version: '3'

services:
  webhook:
    image: holmescode/deploy-webhook:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.port=5000
        - traefik.backend=holmescode-deploy
        - traefik.frontend.rule=Host:www.holmescode.com,holmescode.com;PathPrefixStrip:/deploy
        - traefik.frontend.priority=100
    environment:
      - AMQP_URL=amqp://queue
    networks:
      - ingress
      - private

  listener:
    image: holmescode/deploy-listener:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - LISTENER_AMQPURL=amqp://queue
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - private
  
  queue:
    image: rabbitmq:3.6-alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - private

networks:
  private:
    driver: overlay
  ingress:
    external:
      name: core_ingress
