kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-conf
  namespace: core
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    [kubernetes]
    namespaces = ["core"]
