kind: ConfigMap
apiVersion: 1
metadata:
  name: traefik-conf
  namespace: core
data:
  traefik.toml: |
  defaultEntryPoints = ["http", "https"]
  [entryPoints]
    [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"

    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

  [kubernetes]
    namespaces = ["core", "holmescode", "viper-cloud"]

  [acme]
  email = "matt@holmescode.com"
  storageFile = "/etc/traefik/acme.json"
  onDemand = true
  onHostRule = true
  entryPoint = "https"

  [[acme.domains]]
    main = "beta.holmescode.com"
    sans = ["kube.beta.holmescode.com", "api.beta.holmescode.com", "deploy.beta.holmescode.com"]
  [[acme.domains]]
    main = "beta.viper.cloud"
    sans = ["www.beta.viper.cloud", "api.beta.viper.cloud"]
