kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ingress-controller
  namespace: core
  labels:
    k8s-app: ingress-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: ingress-lb
  template:
    metadata:
      labels:
        k8s-app: ingress-lb
    spec:
      serviceAccountName: ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.7
        name: ingress-lb
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /etc/traefik
          name: certificates
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        args:
          - --api
          - --configfile=/config/traefik.toml
      volumes:
      - name: config
        configMap:
          name: traefik-conf
      - name: certificates
        hostPath:
          path: /etc/traefik
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-service
  namespace: core
spec:
  selector:
    k8s-app: ingress-lb
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: admin
      port: 8080
  type: NodePort
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ingress-web-ui
  namespace: core
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  backend:
    serviceName: ingress-service
    servicePort: admin
