kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ingress-controller
  namespace: core
  labels:
    app: ingress-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingress-lb
  template:
    metadata:
      labels:
        app: ingress-lb
        name: ingress-lb
    spec:
      serviceAccountName: ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.7
        name: ingress-lb
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /etc/traefik
          name: certificates
        ports:
        - name: http
          targetPort: 80
          containerPort: 80
        - name: https
          targetPort: 443
          containerPort: 443
        - name: admin
          targetPort: 8080
          containerPort: 8080
        args:
          - --api
          - --configfile=/config/traefik.toml
        livenessProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
      volumes:
      - name: config
        configMap:
          name: traefik-conf
      - name: certificates
        hostPath:
          path: /etc/traefik
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-service
  namespace: core
spec:
  selector:
    app: ingress-lb
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: admin
      port: 8080
  type: NodePort
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ingress-web-ui
  namespace: core
spec:
  rules:
  - host: beta.holmescode.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ingress-service
          servicePort: admin
