defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "matt@holmescode.com"
storageFile = "/etc/traefik/acme.json"
onDemand = true
onHostRule = true

[[acme.domains]]
  main = "holmescode.com"
  sans = ["www.holmescode.com", "api.holmescode.com", "deploy.holmescode.com"]
[[acme.domains]]
  main = "viper.cloud"
  sans = ["www.viper.cloud", "api.viper.cloud"]
