version: '3'

services:
  web:
    image: holmescode/web:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:        
        - traefik.port=5000
        - traefik.backend=holmescode-web
        - traefik.frontend.rule=Host:www.holmescode.com,holmescode.com
        - traefik.docker.network=core_ingress
    environment:
      - API_URL=https://api.holmescode.com
    networks:
      - ingress
      - private

  api:
    image: holmescode/api:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:        
        - traefik.port=5000
        - traefik.backend=holmescode-api
        - traefik.frontend.rule=Host:api.holmescode.com
        - traefik.docker.network=core_ingress
    environment:
      - MONGO_URL=mongo://db
    networks:
      - ingress
      - private

  db:
    image: mongo:3.4
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /var/db/holmescode:/data/db
    networks:
      - private
  
networks:
  private:
    driver: overlay
  ingress:
    external:
      name: core_ingress
